timgates42/meticulous

README.md, app/meticulous/__main__.py, app/meticulous/_github.py, app/pip/3.6/app/requirements.txt, app/pip/3.7/app/requirements.txt, app/pip/3.8/app/requirements.txt, app/requirements.txt, cookiecutter.json, docs/requirements.txt
=> Support cloning into a directory

app/meticulous/_process.py
=> Add support for preparing a commit

app/meticulous/_process.py
=> Add new options for pr/issue

app/meticulous/_process.py
=> The view url is provided

app/meticulous/_process.py
=> Support multi line diffs by just checking first line

app/meticulous/_process.py
=> Honour EDITOR environment variable

app/meticulous/_process.py
=> Need to wrap editor with plumbum

app/meticulous/_process.py
=> Retain progress in local DB

app/meticulous/_process.py
=> Split words on alphabetic characters only

app/.isort.cfg, app/meticulous/_github.py, app/meticulous/_process.py, docs/spelling_wordlist.txt
=> Do not get archived parent repositories

app/meticulous/version.py
=> Release 0.9.0

README.md, app/meticulous/_process.py, app/meticulous/_sources.py, app/pip/3.6/app/requirements.txt, app/pip/3.7/app/requirements.txt, app/pip/3.8/app/requirements.txt, app/requirements.txt, app/tests/test_process.py, cookiecutter.json, docs/requirements.txt
=> Use requests

app/meticulous/_process.py
=> Ability to display statistics

app/meticulous/_github.py, app/meticulous/_process.py
=> Recheck forked if cache indicates not forked and check parent repos for forking.

app/meticulous/_github.py, app/meticulous/_process.py
=> Check forked parent repos

app/meticulous/_process.py, docs/index.rst, hooks/post_gen_project.sh
=> Alternative editor env

NEWS.rst, app/meticulous/newsfragments/25.feature, app/meticulous/version.py
=> Release 0.9.1

app/meticulous/_process.py, app/pip/3.6/test/requirements.txt, app/pip/3.7/test/requirements.txt, app/pip/3.8/test/requirements.txt
=> Initial automated process step

app/meticulous/_process.py
=> Add get_confirmation call

app/meticulous/_process.py
=> Save json format when checking spelling.

app/meticulous/_process.py
=> Ordered check

app/meticulous/_process.py
=> Initial confirm to automate process

app/meticulous/_process.py
=> Support fixing typos

README.md, app/meticulous/_nonword.py, app/meticulous/_process.py, app/pip/3.6/app/requirements.txt, app/pip/3.7/app/requirements.txt, app/pip/3.8/app/requirements.txt, app/requirements.txt, cookiecutter.json
=> Switch over to standard pr code

app/meticulous/_process.py
=> Fix up resuming processing when a non-word scan is not complete.

app/meticulous/_input.py, app/meticulous/_process.py
=> Pull out input

app/meticulous/_process.py, app/meticulous/_websearch.py, app/meticulous/_websearch_test.py, app/tests/test_websearch.py
=> Add websearch

app/meticulous/_process.py
=> Nicer experience

app/meticulous/_process.py
=> Display above and below lines

TODO.md, app/meticulous/_process.py
=> Version check on startup

TODO.md, app/meticulous/_process.py, app/meticulous/_websearch.py, app/tests/test_websearch.py
=> Minor fixes

app/meticulous/_process.py
=> Use cyan for typo suggestions

TODO.md, app/meticulous/_nonword.py, app/meticulous/_process.py, app/meticulous/_websearch.py, app/tests/test_websearch.py
=> Feature recent nonwords

TODO.md
=> Add manual repo note

app/meticulous/_process.py
=> Avoid branch push failure if bugfix exists

app/meticulous/_process.py
See https://www.conventionalcommits.org/en/v1.0.0/
=> feature: Support conventionalcommits.org

TODO.md, app/meticulous/_sources.py
=> Add awesome-django

app/meticulous/_process.py
=> Require spelling 0.7.0

app/meticulous/_process.py
=> Strip paths

app/meticulous/_process.py, app/meticulous/_summary.py, app/meticulous/_util.py
=> Add fast pr support

app/meticulous/_github.py, app/meticulous/_nonword.py, app/meticulous/_process.py
=> Auto update nonwords

app/meticulous/_process.py
=> Auto rerun and drop remove confirmation

app/meticulous/_input_queue.py, app/meticulous/_input_queue_test.py
=> Add basic user input prioritization

app/meticulous/_input_queue.py, app/meticulous/_input_queue_test.py
=> input save

app/meticulous/_controller.py, app/meticulous/_controller_test.py, app/meticulous/_input_queue.py, app/meticulous/_input_queue_test.py
=> Add basic controller

app/meticulous/_controller.py, app/meticulous/_controller_test.py, app/meticulous/_multiworker.py, app/meticulous/_multiworker_test.py, app/meticulous/_process.py, app/meticulous/_threadpool.py
=> Basic multithread worker processing to just quit

app/meticulous/_controller.py, app/meticulous/_input_queue.py, app/meticulous/_multiworker.py, app/meticulous/_threadpool.py
=> Add support to wait for background tasks

app/meticulous/_controller.py, app/meticulous/_threadpool.py, app/meticulous/_threadpool_test.py
=> Ensure controller passed in threadpool context

app/meticulous/_process.py
=> Call spelling in separate process

app/meticulous/_cleanup.py, app/meticulous/_exceptions.py, app/meticulous/_multiworker.py, app/meticulous/_process.py, app/meticulous/_submit.py
=> Complete basic single task multithreaded queue processing starting point

app/meticulous/_process.py
=> Switch default processing to multiqueue

app/meticulous/_addrepo.py, app/meticulous/_multiworker.py, app/meticulous/_multiworker_test.py, app/meticulous/_process.py, app/meticulous/_submit.py
=> Add missing handler

app/meticulous/_addrepo.py, app/meticulous/_github.py, app/meticulous/_multiworker.py
=> Improve background behaviour

app/meticulous/_addrepo.py, app/meticulous/_multiworker.py, app/meticulous/_submit.py
=> Relocate submit handlers

app/meticulous/_sources.py
=> Exclude repositories owned by people who have requested exemption

app/meticulous/_addrepo.py, app/meticulous/_multiworker.py, app/meticulous/_multiworker_test.py, app/meticulous/_submit.py
=> Background PR submission

app/meticulous/_addrepo.py, app/meticulous/_sources.py
=> Handle deleted repositories

app/meticulous/_multiworker.py, app/meticulous/_nonword.py, app/meticulous/_processrepo.py
=> Background nonwords

app/meticulous/_multiworker.py, app/meticulous/_process.py
=> Add option to clear

app/meticulous/_multiworker.py
=> Adjust active load detection

app/meticulous/_addrepo.py
=> Support repository exhaustion

app/meticulous/_multiworker.py, app/meticulous/_processrepo.py, app/meticulous/_sources.py, app/meticulous/_storage.py, app/meticulous/_summary.py, app/meticulous/_threadpool.py
=> minor polishing

app/meticulous/_processrepo.py, app/meticulous/_sources.py
=> Add sources

app/meticulous/_submit.py
=> Simplify choice between plain PR and issue to save time

app/meticulous/_processrepo.py
=> Display repository completed

app/meticulous/_github.py, app/meticulous/_process.py, app/meticulous/_processrepo.py
=> Support latest spelling release

app/meticulous/_storage.py
=> Store in a directory under the home dir

app/meticulous/_processrepo.py
=> Option to quit

app/meticulous/_websearch.py
=> Bugfix rate limit

app/meticulous/_addrepo.py, app/meticulous/_controller.py, app/meticulous/_input_queue.py, app/meticulous/_multiworker.py, app/meticulous/_processrepo.py, app/meticulous/_progress.py, app/meticulous/_storage.py, app/meticulous/_threadpool.py, app/meticulous/_websearch.py, app/meticulous/_webstate.py
=> Add selection

app/meticulous/_processrepo.py
=> Select word to process next

app/meticulous/_summary.py
=> Replace characters for other content encoding like latin-1

app/meticulous/_webstate.py
=> Fix missing f-string

app/meticulous/_addrepo.py, app/meticulous/_multiworker.py
=> More buffer and non-interactive repository_load

app/meticulous/_progress.py
=> Avoid key error

app/meticulous/_webstate.py
=> Remove webkit appearance on ios

app/meticulous/_processrepo.py
=> Avoid changing line endings

app/meticulous/_addrepo.py
=> Use an interaction at the end of the repositories

app/meticulous/_sources.py
=> Additional repositories

app/meticulous/_github.py, app/meticulous/_nonword.py, app/meticulous/_process.py, app/meticulous/_processrepo.py, app/meticulous/_submit.py
=> Plumbum workaround

app/meticulous/_processrepo.py, app/tests/test_processrepo.py
=> Smarter word replacement

app/meticulous/_processrepo.py
=> Avoid failed git add

app/meticulous/_multiworker.py, app/meticulous/_nonword.py, app/meticulous/_processrepo.py, app/meticulous/_submit.py
=> Display words in files which can't be decoded utf-8 gracefully

app/meticulous/_websearch.py, app/tests/test_websearch.py
=> Strip off very long irregular suggestions

app/meticulous/_sources.py, app/meticulous/_websearch.py, app/tests/test_websearch.py
=> Do not cache repository lists forever
